services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      .env
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres

