export const COMMANDS = {
    return: '🧐 Чем могу вам помочь?',
    next: '➡️ Далее',
    prev: '⬅️ Назад',
    list: '📋 Список Мероприятий',
    create: '✨ Добавить',
    events: '🎊 Мероприятия',
    subscribe: '✅ Записаться',
    unsubscribe: '❌ Отписаться',
    subscribed: '📑 Мои записи',
    delete: '🗑️Удалить',
    update: '✏️Изменить',
    skip: '⏩Пропустить',
    cancel: '❌ Отмена',
    toEvents: '🔙 Назад',
    adminEventsList: '📜Созданные мероприятия',
    subscribers: '👥Записи на мероприятия',
    toEventsList: '📅 Все мероприятия',
    QR: '🔳 Создать QR код',
    Video: '🎥 Отправить кружок',
    makeAdmin: 'Сделать админом 🧐',
}

export const CALLBACKS = {
    next: 'next_event',
    prev: 'prev_event',
    list: 'show_events',
    nextAdmin: 'admin_next',
    prevAdmin: 'prev_admin',
    nextUser: 'next_user',
    prevUser: 'prev_user',
    create: 'create_event',
    update: 'update',
    delete: 'delete_event',
    subscribe: 'subscribe',
    subscribers: 'subscribers',
    unsubscribe: 'unsubscribe',
    toEvents: 'back_to_events',
    toUserEvents: 'user_events',
    adminEventsList: 'list_of_created',
    makeAdmin: 'make_admin',
    QR: 'qr_events',
    Video: 'video',
}
